name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: self-hosted
    # Optionally, if you tagged your runner with "backend-runner", you could use:
    # runs-on: [self-hosted, backend-runner]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Deploy Backend
        working-directory: backend
        run: ./deploy.sh
