name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: self-hosted  # Make sure your self-hosted runner is online.
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'   # Use the required Node.js version.

      # (Optional) Set working directory to backend, if needed.
      - name: Ensure deploy.sh is executable
        working-directory: backend
        run: chmod +x deploy.sh

      - name: Deploy Backend
        working-directory: backend
        run: ./deploy.sh
