name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: self-hosted
    # Optionally, if you tagged your runner with "frontend-runner", use:
    # runs-on: [self-hosted, frontend-runner]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy Frontend
        working-directory: frontend
        run: |
            cd /
            cd /obw-checking/frontend
            ./deploy.sh
