name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: self-hosted
    # Optionally specify labels if your runner is tagged, e.g., [self-hosted, frontend-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test  # If you have tests for your frontend

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy Frontend
        working-directory: frontend
        run: ./deploy.sh
